# Generated by Django 2.2.1 on 2019-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tddtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiments',
            name='word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
