# Generated by Django 2.2.1 on 2019-06-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tddtests', '0002_sentiments_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiments',
            name='goodbad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
