# Generated by Django 2.2.1 on 2019-06-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tddtests', '0003_sentiments_goodbad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiments',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
